default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: development
  host: localhost

test:
  <<: *default
  database: test
  host: localhost

production:
  <<: *default
  database: prod
